name: packme
description: Framework for console server applications
version: 1.1.2
homepage: https://github.com/sourcecaster/packme
repository: https://github.com/sourcecaster/packme
issue_tracker: https://github.com/sourcecaster/packme/issues
documentation: https://github.com/sourcecaster/packme
environment:
  sdk: ">=2.13.0 <3.0.0"
executables:
  compile: compile