name: packme
description: PackMe is a lightweight library for packing your data into binary buffer (presumably in order to be sent over TCP connection) and unpacking it back to class objects described in a simple way via JSON manifest files.
version: 1.1.3
homepage: https://github.com/sourcecaster/packme
repository: https://github.com/sourcecaster/packme
issue_tracker: https://github.com/sourcecaster/packme/issues
documentation: https://github.com/sourcecaster/packme
environment:
  sdk: ">=2.13.0 <3.0.0"
dev_dependencies:
  test: ^1.17.11